export const CHANGE_MESSAGE_INPUT = 'CHANGE_MESSAGE_INPUT';

export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const CHANGE_PASSWORD_CONFIRMATION = 'CHANGE_PASSWORD_CONFIRMATION';

export const CHANGE_SIGNIN_STATE = 'CHANGE_SIGNIN_STATE';

export const USER_NAME_ERROR = 'USER_NAME_ERROR';

export const PASSWORD_ERROR = 'PASSWORD_ERROR';

export const PASSWORD_CONFIRMATION_ERROR = 'PASSWORD_CONFIRMATION_ERROR';